/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 29 16:59:36 GMT 2020
 */

package edu.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.impl.WeightHelper;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WeightHelper_ESTest extends WeightHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(4233.282052);
      assertEquals("Obese", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(25.1);
      assertEquals("Overweight", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(25.0);
      assertNotNull(string0);
      assertEquals("Normal", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(18.5);
      assertEquals("Normal", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SystemInUtil.addInputLine("9");
      String[] stringArray0 = new String[3];
      WeightHelper.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI(0.0, 1510.96493788164);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI(29.9, (-6229.81));
      assertEquals(7.704094215957299E-7, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("Obese");
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        WeightHelper.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(Double.NaN);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory((-1540.3719205977864));
      assertNotNull(string0);
      assertEquals("Underweight", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI((-1.0), (-1.0));
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(29.9);
      assertEquals("Overweight", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(30.0);
      assertEquals("Obese", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        WeightHelper.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("0");
      String[] stringArray0 = new String[4];
      WeightHelper.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }
}
